### ISSUE TITLE
一个是弹幕打印问题

### ISSUE THREAD

**Issue by daofeng2015** [flxxyz/douyudm#11]
我用的时候怎么感觉有时候会漏弹幕的情况,慢慢调试后发现如果一个弹幕解码后有多条弹幕消息,打印出来只显示一个
![QQ截图20200612225722](https://user-images.githubusercontent.com/14891398/84516446-64256900-ad00-11ea-899a-e3ea6db223b7.png)

**Comment by flxxyz** [comment]
调试发现应该是**Promise**异步处理的问题，可以尝试更新到最新版本 `v1.1.2-beta.5` 使用

具体浏览[v1.1.2-beta.5](https://github.com/flxxyz/douyudm/releases/tag/v1.1.2-beta.5)

**Comment by daofeng2015** [comment]
> 调试发现应该是**Promise**异步处理的问题，可以尝试更新到最新版本 `v1.1.2-beta.5` 使用
> 
> 具体浏览[v1.1.2-beta.5](https://github.com/flxxyz/douyudm/releases/tag/v1.1.2-beta.5)

还有一点就是 最后返回的弹幕对象中的还是有@A和@S没处理干净
![QQ截图20200614000416](https://user-images.githubusercontent.com/14891398/84573445-0746b300-add3-11ea-8236-3c0c7954b015.png)

**Comment by flxxyz** [comment]
> > 调试发现应该是**Promise**异步处理的问题，可以尝试更新到最新版本 `v1.1.2-beta.5` 使用
> > 具体浏览[v1.1.2-beta.5](https://github.com/flxxyz/douyudm/releases/tag/v1.1.2-beta.5)
> 
> 还有一点就是 最后返回的弹幕对象中的还是有@A和@s没处理干净
> ![QQ截图20200614000416](https://user-images.githubusercontent.com/14891398/84573445-0746b300-add3-11ea-8236-3c0c7954b015.png)

这个问题明天修复
