### ISSUE TITLE
优化斗鱼STT

### ISSUE THREAD

**Issue by flxxyz** [flxxyz/douyudm#14]
- [x] 反序列化对一级元素的值无法再进行反序列化

问题: #11

**Comment by daofeng2015** [comment]
这是从斗鱼h5弹幕页中找到的stt序列化的部分代码
e为处理好的弹幕信息,例如:"type@=chatmsg/rid@=74751/ct@=1/uid@=10598109/nn@=Liar左/txt@=？？？？？？？？/cid@=f4b3a7c4b4ac49e6c24d3a0000000000/ic@=avatar_v3@S202003@S5deadea40a214e19990b3e6ea126bc8d/level@=24/sahf@=0/cst@=1592117619849/bnn@=339/bl@=15/brid@=485503/hc@=4434719c2bf09ce9171d09e240a4896f/cbid@=65210/el@=/lk@=/urlev@=14/dms@=5/pdg@=48/pdk@=92/"

decode: function(e) {
                    var t = [];
                    function n(e) {
                        var t = [];
                        "/" != e.charAt(e.length - 1) && (e += "/");
                        for (var n, r = "", i = "", o = 0, a = e.length; o < a; o++)
                            "/" === e.charAt(o) ? (n = {
                                key: r,
                                value: i
                            },
                            t.push(n),
                            r = i = "") : "@" === e.charAt(o) ? (o++,
                            "A" === e.charAt(o) ? i += "@" : "S" === e.charAt(o) ? i += "/" : "=" === e.charAt(o) && (r = i,
                            i = "")) : i += e.charAt(o);
                        return t
                    }
                    return (e = String(e)) && 1 === (t = n(e)).length && /@=/g.test(t[0].value) && (t = n(t[0].value)),
                    t.get = function(e) {
                        return o(this, e)
                    }
                    ,
                    t.too = function() {
                        return a(this)
                    }
                    ,
                    t
                }
