### ISSUE TITLE
礼物信息全吗？

### ISSUE THREAD

**Issue by consciousgaze** [flxxyz/douyudm#2]
你获取的礼物信息全吗？我似乎获取不到荧光棒啊之类的小礼物。要办卡以上才会显示送礼物。
而后loginreq里面那个dfl你知道是做什么的吗？

**Comment by flxxyz** [comment]
因为礼物实在太多了，我无法全部收集，我可以给你我现在已经收集到的一些礼物id
```
room.on('dgb', function (res) {
    //斗鱼的礼物过多无法全部记录，20000以后可以判断为鱼翅购买，其他为系统赠送
    const gifts = {
        20000: '鱼丸',
        20001: '弱鸡',
        20002: '办卡',
        20003: '飞机',
        20004: '火箭',
        20005: '超级火箭',
        20006: '赞',
        20008: '超大丸星',
        20234: '爱心飞机',
        20387: '心动火箭',
        20417: '福袋',
        20541: '大气',
        20542: '666',
        20618: '魔法戒指',
        20624: '魔法彩蛋',
        20642: '能量电池',
        20643: '能量水晶',
        20644: '能量戒指',
        20710: '金鲨鱼',
        20725: '宠爱卡',
        20726: '挚爱超火',
        20727: '乖乖戴口罩',
        20728: '勤洗手',
        192: '赞(系统)',
        193: '弱鸡(系统)',
        519: '呵呵(系统)',
        520: '稳(系统)',
        712: '棒棒哒(系统)',
        714: '怂(系统)',
        824: '应援棒(系统)',
    }
    const gift = gifts[res.gfid] || '其他礼物'
    console.log('[dgb]', `感谢${res.nn}送出${gift}`, `礼物id=${res.gfid}`)
})
```

**Comment by flxxyz** [comment]
如果你在哪里能够确定礼物id，可以留言我去整合起来

**Comment by consciousgaze** [comment]
哦哦。你误会了。每个房间的礼物信息可以通过https://open.douyucdn.cn/api/RoomApi/room/<room_id>获得。

不过这里的问题是dgb好像不会包含办卡以下的礼物信息。如果有人送荧光棒就看不到。你试过可以吗？

**Comment by flxxyz** [comment]
> 哦哦。你误会了。每个房间的礼物信息可以通过https://open.douyucdn.cn/api/RoomApi/room/<room_id>获得。
> 
> 不过这里的问题是dgb好像不会包含办卡以下的礼物信息。如果有人送荧光棒就看不到。你试过可以吗？

办卡我不清楚，不过赠送礼物在“dgb”事件里都会出现

**Comment by consciousgaze** [comment]
> > 哦哦。你误会了。每个房间的礼物信息可以通过https://open.douyucdn.cn/api/RoomApi/room/<room_id>获得。
> > 不过这里的问题是dgb好像不会包含办卡以下的礼物信息。如果有人送荧光棒就看不到。你试过可以吗？
> 
> 办卡我不清楚，不过赠送礼物在“dgb”事件里都会出现

你试过吗？用的哪个直播间做的例子？我只能看到办卡和飞机什么的。荧光棒什么的都看不到。

**Comment by flxxyz** [comment]
科技美学`452628`, 解说拒绝`102965`，这两个。
你可以用`example/web`做做测试
![test.png](https://i.loli.net/2020/04/20/JHlt9FmSRgALnOd.png)

**Comment by consciousgaze** [comment]
好谢谢。那我可能哪里设置错了
