### ISSUE TITLE
有办法区分开播rss是直播还是轮播录像吗？

### ISSUE THREAD

**Issue by cnSchwarzer** [flxxyz/douyudm#34]

**Comment by cnSchwarzer** [comment]
有办法，通过获取`https://www.douyu.com/wgapi/live/liveweb/getRoomLoopInfo?rid={RoomId}`，判断`string.IsNullOrWhiteSpace(JObject.Parse(r)["data"]["vid"].Value<string>())`即可

**Comment by flxxyz** [comment]
其实可以通过斗鱼自身开放平台的接口获取，信息也更丰富 https://open.douyucdn.cn/

link: https://open.douyucdn.cn/api/RoomApi/room/4496540

> 下面这个是我镜像他们平台的接口，处理了浏览器跨域
> https://mirror.flxxyz.com/douyu/api/RoomApi/room/4496540
