### ISSUE TITLE
解码出错，貌似Unescape和Escape顺序有问题？

### ISSUE THREAD

**Issue by cnSchwarzer** [flxxyz/douyudm#36]
type@=frank/fc@=9493/bnn@=屁屁王/list@=uid@AA=66038266@ASnn@AA=需要保密的情話@ASic@AA=avatar_v3@AAS202011@AAS2ceaf3b64d7842f1b10d33febc2b92d0@ASfim@AA=100000000@ASbl@AA=30@ASlev@AA=83@ASpg@AA=1@ASrg@AA=4@ASnl@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=1027024@ASnn@AA=认真学习天天开心@ASic@AA=avatar_v3@AAS202012@AAS8d3dded0c19c4fb4afca1cf855d1f901@ASfim@AA=86449650@ASbl@AA=29@ASlev@AA=100@ASpg@AA=1@ASrg@AA=4@ASnl@AA=7@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=35770124@ASnn@AA=Liangbibi@ASic@AA=avatar_v3@AAS201910@AAS3b6a6dd0c7d8402c95fa6dc02eb9c51c@ASfim@AA=22314710@ASbl@AA=24@ASlev@AA=42@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=4710398@ASnn@AA=直播间最帅的啊牛@ASic@AA=avatar_v3@AAS202004@AASb597615804794767bfa719c2e540d770@ASfim@AA=20091600@ASbl@AA=23@ASlev@AA=50@ASpg@AA=1@ASrg@AA=4@ASnl@AA=3@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=90339044@ASnn@AA=意大利小方饺@ASic@AA=avatar_v3@AAS202005@AAScaa959e3903b4e298e7ce835c5e375bb@ASfim@AA=18892800@ASbl@AA=23@ASlev@AA=42@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=41434104@ASnn@AA=千叶的不良少年@ASic@AA=avatar_v3@AAS202011@AASe56a2b14431e426f8cbb053e950a5700@ASfim@AA=18623100@ASbl@AA=23@ASlev@AA=68@ASpg@AA=1@ASrg@AA=4@ASnl@AA=7@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=163647552@ASnn@AA=热心市民老何@ASic@AA=avatar_v3@AAS202012@AAS492ac991bb664ad194781ccf450ab22f@ASfim@AA=17733800@ASbl@AA=23@ASlev@AA=47@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=84090929@ASnn@AA=歪崽崽崽崽崽崽崽@ASic@AA=avatar_v3@AAS202012@AASa43114aec204416a87ecc0332f53dc60@ASfim@AA=14917240@ASbl@AA=22@ASlev@AA=71@ASpg@AA=1@ASrg@AA=4@ASnl@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=328986176@ASnn@AA=可可爱爱仓鼠球呀@ASic@AA=avatar_v3@AAS202007@AASb9de5ed9c572494ca96b085610960f1a@ASfim@AA=13947400@ASbl@AA=21@ASlev@AA=58@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=144227921@ASnn@AA=眉梢逢雪@ASic@AA=avatar_v3@AAS202010@AASff7f41e8f1394b1c99fa02f11325564a@ASfim@AA=13812640@ASbl@AA=21@ASlev@AA=41@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@S/ver@=150166/ci@=14lwtgzw0o/rid@=4496540/

**Comment by cnSchwarzer** [comment]
#37

**Comment by flxxyz** [comment]
![image](https://user-images.githubusercontent.com/8678079/103451360-2fa9e680-4cfe-11eb-80f6-d49afbfe3db0.png)

其实这个有关头像的字段没有被解析出来，我正在处理中

**Comment by flxxyz** [comment]
![image](https://user-images.githubusercontent.com/8678079/103451397-b1017900-4cfe-11eb-8147-53dc38bc489e.png)

你抛出的这段字符串是原始消息？

**Comment by flxxyz** [comment]
```
type@=frank/fc@=4395/bnn@=拒绝R/list@=uid@AA=197290249@ASnn@AA=宋宋宋555@ASic@AA=avatar_v3@AAS201809@AASde94cadbaa975630940499fdbafbf258@ASfim@AA=74078400@ASbl@AA=28@ASlev@AA=52@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=216851315@ASnn@AA=滴滴么么儿@ASic@AA=avatar_v3@AAS202006@AASf4f65dbd49cf44da944f657fd934c094@ASfim@AA=22429300@ASbl@AA=24@ASlev@AA=41@ASpg@AA=1@ASrg@AA=4@ASnl@AA=7@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=177076498@ASnn@AA=橘井仁心@ASic@AA=avanew@AASface@AAS201711@AAS13@AAS19@AAS0b33a9f10246b83ca9527fb8efdc132f@ASfim@AA=16192900@ASbl@AA=22@ASlev@AA=38@ASpg@AA=1@ASrg@AA=4@ASnl@AA=7@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=163415865@ASnn@AA=HArianaC@ASic@AA=avatar_v3@AAS202005@AASd21cfac310a04a2fb76ed17a8d80040d@ASfim@AA=14609100@ASbl@AA=22@ASlev@AA=39@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=172172693@ASnn@AA=不要昵称12@ASic@AA=avanew@AASface@AAS201710@AAS13@AAS15@AASd1f39c4b83e2eb4cc55c09a174cb1744@ASfim@AA=12552160@ASbl@AA=21@ASlev@AA=39@ASpg@AA=1@ASrg@AA=4@ASnl@AA=7@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=193517041@ASnn@AA=风暴中的汉堡@ASic@AA=avatar_v3@AAS201807@AASb047ee52079c53aedf0760177ade0c16@ASfim@AA=10228360@ASbl@AA=20@ASlev@AA=40@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=25190947@ASnn@AA=无畏孤独狼@ASic@AA=avatar_v3@AAS201809@AAS992cd2a66f66952c8b8afa4267d2f160@ASfim@AA=9686340@ASbl@AA=20@ASlev@AA=38@ASpg@AA=1@ASrg@AA=4@ASnl@AA=7@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=39270085@ASnn@AA=看见你是我的荣耀@ASic@AA=avatar@AAS039@AAS27@AAS00@AAS85_avatar@ASfim@AA=9559080@ASbl@AA=20@ASlev@AA=37@ASpg@AA=1@ASrg@AA=4@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=37862064@ASnn@AA=JC小猫@ASic@AA=avatar_v3@AAS201906@AASd94deeed8c8d43c7b09afc673e733daa@ASfim@AA=9284120@ASbl@AA=20@ASlev@AA=40@ASpg@AA=1@ASrg@AA=4@ASnl@AA=1@ASsahf@AA=0@ASnewrg@AA=0@AS@Suid@AA=227676692@ASnn@AA=董旺成@ASic@AA=avatar_v3@AAS202003@AAS5548b1db5ee1481fa8d8828d5fc2ee80@ASfim@AA=8120680@ASbl@AA=19@ASlev@AA=39@ASpg@AA=1@ASrg@AA=4@ASnl@AA=7@ASsahf@AA=0@ASnewrg@AA=0@AS@S/ver@=156739/ci@=r6ddzwf2uy/rid@=102965/
```

我这里也有一段原始的 **frank** 消息
