### ISSUE TITLE
你有试过发送弹幕吗？

### ISSUE THREAD

**Issue by consciousgaze** [flxxyz/douyudm#4]
我看弹幕发送也曾经有人用websocket做出来过。https://github.com/pelucky/DouyuDanmu/tree/master

不过服务器地址似乎变了。我不太会用wireshark也从那么多package里面找不到发送弹幕的packet。你做过尝试吗？

**Comment by flxxyz** [comment]
不好意思，没考虑发送弹幕，我一开始的初衷只是用于浏览弹幕

**Comment by flxxyz** [comment]
发送弹幕的思路是构建`chatmsg`消息结构，其中一个字段`txt@=弹幕内容`
