### ISSUE TITLE
已结束

### ISSUE THREAD

**Issue by chenguaself** [flxxyz/douyudm#40]

**Comment by flxxyz** [comment]
ok，我业余时间支持一下，你可以关注后续进度

**Comment by zxwanghongyi** [comment]
问一下有可能做成可以把记录的弹幕输出成ass的弹幕字幕格式吗 像斗鱼官方的录像功能一样 给了个flv和一个ass字幕， 现在网上的自动录播软件要么不能同步录弹幕，斗鱼官方这个又不能自动录。

**Comment by flxxyz** [comment]
> 问一下有可能做成可以把记录的弹幕输出成ass的弹幕字幕格式吗 像斗鱼官方的录像功能一样 给了个flv和一个ass字幕， 现在网上的自动录播软件要么不能同步录弹幕，斗鱼官方这个又不能自动录。

字幕这种是依据时间轴来记录的，可能还要看看有什么方法能够知道主播的开播时间点，或者是从某一个时间点开始直播的。

还有 ass 格式字幕这个我可能要了解一下怎么封装。

**Comment by zxwanghongyi** [comment]
`[Script Info]
Title: Douyu
ScriptType: v4.00+
PlayResX: 1280
PlayResY: 720

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold,Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: 弹幕,SimHei,30,&H00FFFFFF,&H00FFFFFF,&H00000000,&HFFFFFFFF,-1,0,0,0,100,100,0,0,1,1,2,7,10,0,10,1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
Dialogue: 0,0:0:0.15,0:0:15.15,弹幕,,0,0,0,,{\move(1280,20,-205,20)} 321
Dialogue: 0,0:0:0.78,0:0:15.78,弹幕,,0,0,0,,{\1c&H00b469ff}{\move(1280,59,-438,59)} 123`
这个是斗鱼客户端录的ass的格式

**Comment by zxwanghongyi** [comment]
问下有办法过滤一下机器人弹幕吗 我看这些机器人弹幕后面这一串信息都是空的

```
{
      "timestamp": 1618302363635,
      "message": "type@=chatmsg/rid@=290935/ct@=1/uid@=259641766/nn@=机器人弹幕/txt@=听指挥能赢/cid@=cb6e2b02fff94bdb9470a50400000000/ic@=avatar_v3@S201904@S6a0ddf5e53d547cfa8f127feb78c23ba/level@=12/sahf@=0/cst@=1618302361/bnn@=/bl@=0/brid@=0/hc@=/el@=/lk@=/pdg@=58/pdk@=23/ext@=/"
    },
    {
      "timestamp": 1618302363847,
      "message": "type@=chatmsg/rid@=290935/ct@=1/uid@=6384263/nn@=真人/txt@=想死你了表妹/cid@=2a36ca85497f41114cbf4b0000000000/ic@=avatar_v3@S202104@S7ad4cdf091844396a6fb22d7e79e11ed/level@=34/sahf@=0/col@=1/cst@=1618302360591/bnn@=粉丝牌/bl@=21/brid@=290935/hc@=c9dee25e7897a464272b80678de6ea8b/hl@=1/ifs@=1/cbid@=502719/el@=/lk@=/fl@=21/urlev@=18/dms@=6/pdg@=70/pdk@=77/ext@=/"
    },
```

**Comment by zxwanghongyi** [comment]
我觉得可以做成 用别的软件录下来视频流之后 用户手动输入一段视频的开始和结束时间 然后根据时间戳把这部分弹幕提取出来导出成ass

**Comment by flxxyz** [comment]
> 问下有办法过滤一下机器人弹幕吗 我看这些机器人弹幕后面这一串信息都是空的
> 
> ```
> {
>       "timestamp": 1618302363635,
>       "message": "type@=chatmsg/rid@=290935/ct@=1/uid@=259641766/nn@=机器人弹幕/txt@=听指挥能赢/cid@=cb6e2b02fff94bdb9470a50400000000/ic@=avatar_v3@S201904@S6a0ddf5e53d547cfa8f127feb78c23ba/level@=12/sahf@=0/cst@=1618302361/bnn@=/bl@=0/brid@=0/hc@=/el@=/lk@=/pdg@=58/pdk@=23/ext@=/"
>     },
>     {
>       "timestamp": 1618302363847,
>       "message": "type@=chatmsg/rid@=290935/ct@=1/uid@=6384263/nn@=真人/txt@=想死你了表妹/cid@=2a36ca85497f41114cbf4b0000000000/ic@=avatar_v3@S202104@S7ad4cdf091844396a6fb22d7e79e11ed/level@=34/sahf@=0/col@=1/cst@=1618302360591/bnn@=粉丝牌/bl@=21/brid@=290935/hc@=c9dee25e7897a464272b80678de6ea8b/hl@=1/ifs@=1/cbid@=502719/el@=/lk@=/fl@=21/urlev@=18/dms@=6/pdg@=70/pdk@=77/ext@=/"
>     },
> ```

机器人弹幕可能没办法过滤掉，这里只是接收方，无法验证这个弹幕信息是不是机器人发送的

**Comment by flxxyz** [comment]
> ```
> [Script Info]
> Title: Douyu
> ScriptType: v4.00+
> PlayResX: 1280
> PlayResY: 720
> 
> [V4+ Styles]
> Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold,Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
> Style: 弹幕,SimHei,30,&H00FFFFFF,&H00FFFFFF,&H00000000,&HFFFFFFFF,-1,0,0,0,100,100,0,0,1,1,2,7,10,0,10,1
> 
> [Events]
> Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
> Dialogue: 0,0:0:0.15,0:0:15.15,弹幕,,0,0,0,,{\move(1280,20,-205,20)} 321
> Dialogue: 0,0:0:0.78,0:0:15.78,弹幕,,0,0,0,,{\1c&H00b469ff}{\move(1280,59,-438,59)} 123
> ```
> 
> 这个是斗鱼客户端录的ass的格式

斗鱼这种格式我去研究一下，有可实现方案再回复

**Comment by flxxyz** [comment]
> 我觉得可以做成 用别的软件录下来视频流之后 用户手动输入一段视频的开始和结束时间 然后根据时间戳把这部分弹幕提取出来导出成ass

你说的这个方案确实可行，具体操作可能是 `douyudm convert ass <start time> <end time>`
