### ISSUE TITLE
长时间运行会收不到下播提醒

### ISSUE THREAD

**Issue by cnSchwarzer** [flxxyz/douyudm#6]
如题，试了两天都这样。主播下播收不到rss，但能收到弹幕

**Comment by flxxyz** [comment]
![QQ截图20200511005713](https://user-images.githubusercontent.com/8678079/81505528-6ae84700-9322-11ea-8501-032bf197fb47.png)

能接收到`rss`事件

**Comment by flxxyz** [comment]
刚刚将库更新至`v1.1.0`，增加了调试模式，能将弹幕服务器推送的所有消息保存到文件(包括未知的消息事件)

具体浏览[README](https://github.com/flxxyz/douyudm#%E4%BD%BF%E7%94%A8%E5%91%BD%E4%BB%A4%E8%A1%8C)
