### ISSUE TITLE
能否支持下emoji表情?

### ISSUE THREAD

**Issue by daofeng2015** [flxxyz/douyudm#7]
不指望能支持斗鱼自己的表情,但是emoji可以支持下吗？

**Comment by flxxyz** [comment]
### linux
![linux](https://user-images.githubusercontent.com/8678079/82481830-8284b400-9b08-11ea-962f-2302465f382f.png)

### windows cmd
![windows cmd](https://user-images.githubusercontent.com/8678079/82482158-fb840b80-9b08-11ea-9f27-f9a8baed14bd.png)

### windows powershell
![windows powershell](https://user-images.githubusercontent.com/8678079/82482897-202cb300-9b0a-11ea-88e2-be80b902cc37.png)


如果是以cli方式运行，你需要考虑的是终端的字符集是否支持emoji

**Comment by daofeng2015** [comment]
> ### linux
> ![linux](https://user-images.githubusercontent.com/8678079/82481830-8284b400-9b08-11ea-962f-2302465f382f.png)
> 
> ### windows cmd
> ![windows cmd](https://user-images.githubusercontent.com/8678079/82482158-fb840b80-9b08-11ea-9f27-f9a8baed14bd.png)
> 
> ### windows powershell
> ![windows powershell](https://user-images.githubusercontent.com/8678079/82482897-202cb300-9b0a-11ea-88e2-be80b902cc37.png)
> 
> 如果是以cli方式运行，你需要考虑的是终端的字符集是否支持emoji
斗鱼那个礼物有个专门的json文件,你获取后,循环读取就行了,不需要再本地写死

**Comment by flxxyz** [comment]
> > ### linux
> > ![linux](https://user-images.githubusercontent.com/8678079/82481830-8284b400-9b08-11ea-962f-2302465f382f.png)
> > ### windows cmd
> > ![windows cmd](https://user-images.githubusercontent.com/8678079/82482158-fb840b80-9b08-11ea-9f27-f9a8baed14bd.png)
> > ### windows powershell
> > ![windows powershell](https://user-images.githubusercontent.com/8678079/82482897-202cb300-9b0a-11ea-88e2-be80b902cc37.png)
> > 如果是以cli方式运行，你需要考虑的是终端的字符集是否支持emoji
> > 斗鱼那个礼物有个专门的json文件,你获取后,循环读取就行了,不需要再本地写死

没有支持读取礼物的相关功能，演示代码里只用于调试dgb事件内容，请不要混为一谈，还有消息内容全部为原始消息。
